### ISSUE TITLE
Support for Angular v17

### ISSUE THREAD

**Issue by kgish** [ocombe/ng2-translate#1460]
I have updated our company application to angular v17 and unfortunately cannot get ngx-translate working.

The problem is that `ngModule` is no longer used so one has to modify the `app.config.ts` file.

This is a show-stopper for us, so hopefully this can be fixed soon.

Thanks in advance for your help.

**Comment by ocombe** [comment]
What do you mean `ngModule` is no longer used?

**Comment by ahmedalmorsy1993** [comment]
I am using angular17 when trying to use the translation key with translate pip it gets back the error translate pip does not exist
![Screenshot from 2023-12-03 12-31-10](https://github.com/ngx-translate/core/assets/110463015/75f7b623-40f3-4a55-b80d-d8fac8c317af)

and this configuration
![Screenshot from 2023-12-03 12-32-18](https://github.com/ngx-translate/core/assets/110463015/f129cb62-1435-4973-a0ff-0d03aa4ed8b5)

**Comment by kgish** [comment]
Thanks, now working!

**Comment by ahmedalmorsy1993** [comment]
> Thanks, now working!

should I update my project now to work with me?

**Comment by platinumsolutionsithelp** [comment]
@ahmedalmorsy1993 did you manage to fix the html and how?

**Comment by gultyayev** [comment]
@ahmedalmorsy1993 you have not imported pipe/module containing pipe in your standalone component.

**Comment by ShailaPatilacmeconnect** [comment]
i updated my project to angular 17 and getting errors for translate pipe and many other. "@ngx-translate/core": "^15.0.0","angularx-qrcode": "^17.0.0",
![image](https://github.com/ngx-translate/core/assets/96560667/cc470c63-c0bd-4e85-8ee6-decbd4e7365f)
![image](https://github.com/ngx-translate/core/assets/96560667/735c3158-e16e-4a2d-9723-e9467ebd155e)

**Comment by hpardess** [comment]
Here is how it worked for me...
app.config.ts
```
// AoT requires an exported function for factories
export function HttpLoaderFactory(httpClient: HttpClient) {
  return  new  TranslateHttpLoader(httpClient, './assets/i18n/', '.json');
}

export const provideTranslation = () => ({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient],
  },
});

export const appConfig: ApplicationConfig = {
  providers: [
    provideAnimations(), // required animations providers
    provideHttpClient(),
    importProvidersFrom([
      HttpClientModule, 
      TranslateModule.forRoot(provideTranslation())
    ]),
    provideRouter(routes),
    
  ]
};
```

**Comment by muhamedkarajic** [comment]
I get following issue:
<img width="666" alt="image" src="https://github.com/ngx-translate/core/assets/35216938/96146c5e-197f-46ee-a1fc-0fb5480f5784">

**Comment by muhamedkarajic** [comment]
> Maybe this helps, this works for me, although in a small toy-level app:
> 
> in your `app.config.ts`
> 
> ```ts
> // required for AoT 
> export function HttpLoaderFactory(http: HttpClient) {
>   return new TranslateHttpLoader(http);
> }
> 
> export const appConfig: ApplicationConfig = {
>   providers: [provideAnimations(), provideHttpClient(),
>     TranslateModule.forRoot({
>       defaultLanguage: 'en',
>       loader: {
>         provide: TranslateLoader,
>         useFactory: HttpLoaderFactory,
>         deps: [HttpClient]
>       }
>     }).providers!]
> };
> ```
> 
> Note the ! at the end (basically casts away or suppresses the potential `undefined`)
> 
> Here is the relevant package.json
> 
> ```json
>     "@ngx-translate/core": "^15.0.0",
>     "@ngx-translate/http-loader": "^8.0.0"
> ```
> 
> Now I can just use the pipe for example in a template. Your component needs to import the TranslateModule.

This dose not solve my issue:
> No provider for TranslateService!

**Comment by muhamedkarajic** [comment]
Any news on this?

**Comment by tehcmanmax** [comment]
> This dose not solve my issue. Error thrown is:
> 
> > No provider for TranslateService!

Did you do the import of TranslateModule in the components where you want to use the pipe?


At TS:
```ts
import {Component} from '@angular/core';
import {TranslateModule} from '@ngx-translate/core'; <----- this


@Component({
  selector: 'app-home',
  standalone: true,
  imports: [TranslateModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.scss'
})
export class HomeComponent {

}

```
At HTML
```
<section id="home" class="full-height px-lg-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-10">
        <h1 class="display-4 fw-bold" data-aos="fade-up">
          {{'HOME.IMMIGRATION' | translate}}         </h1>.   <----------- this

```

**Comment by muhamedkarajic** [comment]
> > This dose not solve my issue. Error thrown is:
> > > No provider for TranslateService!
> 
> @muhamedkarajic Did you do the import of TranslateModule in the components where you want to use the pipe?
> 
> At TS:
> 
> ```ts
> import {Component} from '@angular/core';
> import {TranslateModule} from '@ngx-translate/core'; <----- this
> 
> 
> @Component({
>   selector: 'app-home',
>   standalone: true,
>   imports: [TranslateModule],
>   templateUrl: './home.component.html',
>   styleUrl: './home.component.scss'
> })
> export class HomeComponent {
> 
> }
> ```
> 
> At HTML
> 
> ```
> <section id="home" class="full-height px-lg-5">
>   <div class="container">
>     <div class="row">
>       <div class="col-lg-10">
>         <h1 class="display-4 fw-bold" data-aos="fade-up">
>           {{'HOME.IMMIGRATION' | translate}}         </h1>.   <----------- this
> ```

I know how to import the module in a standalone enviroment, none of what you are saying is new to me. For me from what I understood the translation module needs to be updated to angular 17 so it supports the esmodule build functionality. Thats what I'm asking for.

**Comment by muhamedkarajic** [comment]
@ocombe any news man?

**Comment by ocombe** [comment]
There is no config specific to esmodule, it works exactly like webpack for Angular code.
You can use `importProvidersFrom` to get the providers from ngx translate:
```ts
importProvidersFrom(TranslateModule.forRoot({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    deps: [HttpClient],
    useFactory: HttpLoaderFactory
  }
}))
```

If you see an error with `TranslateFakeLoader` it's weird. You can just directly use the providers that the module was exporting originally, the `forRoot` function isn't complicated: https://github.com/ngx-translate/core/blob/master/packages/core/public-api.ts#L51-L60

**Comment by MartinFerret** [comment]
I'm curious guys to know if your configuration allows the translation in ts files through the TranslateService. I think it doesn't because the async, it probably returns thr key instead of the value.

**Comment by Prasanta651** [comment]
> Even better, thanks!

please share the solution i am facing same issue.

**Comment by TonyStarkGR** [comment]
Hello, I'm facing the same issue and I've followed your instructions so far. Also I've tried to tinker around a bit, but with no luck....this is what I have so far

the **app.config.ts** file

`import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideClientHydration } from '@angular/platform-browser';
import { provideHttpClient, HttpClient, HttpBackend, HttpClientModule, withFetch } from '@angular/common/http';
import { provideAnimations } from '@angular/platform-browser/animations';
import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export const provideTranslation = () => ({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpBackend, HttpClient],
  },
});

export function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, "./assets/i18n/", ".json");
}

export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes), 
    provideClientHydration(),
    provideAnimations(), 
    provideHttpClient(withFetch()),
    importProvidersFrom([
      HttpClientModule, 
      TranslateModule.forRoot(provideTranslation()),
      TranslateModule.forChild(provideTranslation())
    ]),]
};`

and that's the error I get when I run ng serve

`ERROR TypeError: this.http.get is not a function
    at TranslateHttpLoader.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/http-loader/dist/fesm2022/ngx-translate-http-loader.mjs:14:26)
    at _TranslateService.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:454:52)
    at _TranslateService.retrieveTranslations (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:443:81)
    at _TranslateService.setDefaultLang (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:392:24)
    at _TranslateService (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:382:12)
    at Object.TranslateService_Factory (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:708:12)
    at eval (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5239:43)
    at runInInjectorProfilerContext (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:3644:9)
    at R3Injector.hydrate (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5238:17)
    at R3Injector.get (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5106:33)
TypeError: this.http.get is not a function
    at TranslateHttpLoader.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/http-loader/dist/fesm2022/ngx-translate-http-loader.mjs:14:26)
    at _TranslateService.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:454:52)
    at _TranslateService.retrieveTranslations (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:443:81)
    at _TranslateService.setDefaultLang (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:392:24)
    at _TranslateService (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:382:12)
    at Object.TranslateService_Factory (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:708:12)
    at eval (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5239:43)
    at runInInjectorProfilerContext (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:3644:9)
    at R3Injector.hydrate (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5238:17)
    at R3Injector.get (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5106:33)
7:49:19 μ.μ. [vite] Internal server error: this.http.get is not a function
      at TranslateHttpLoader.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/http-loader/dist/fesm2022/ngx-translate-http-loader.mjs:14:26)
      at _TranslateService.getTranslation (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:454:52)
      at _TranslateService.retrieveTranslations (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:443:81)
      at _TranslateService.setDefaultLang (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:392:24)
      at _TranslateService (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:382:12)
      at Object.TranslateService_Factory (c:/GitProjects/BrokerAgentUI/node_modules/@ngx-translate/core/dist/fesm2022/ngx-translate-core.mjs:708:12)
      at eval (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5239:43)
      at runInInjectorProfilerContext (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:3644:9)
      at R3Injector.hydrate (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5238:17)
      at R3Injector.get (c:/GitProjects/BrokerAgentUI/node_modules/@angular/core/fesm2022/core.mjs:5106:33)`

I'm using Angular 17.2.1 with the latest version of ngx-translate

**Comment by geo242** [comment]
@ocombe Will there be a provide function added in the near future so that we don't have to use `importProvidersFrom`?

**Comment by jishnutv** [comment]
> TypeError: this.http.get is not a function
>     at TranslateHttpLoader.getTranslation

Please remove `HttpBackend` from `deps`

**Comment by ahmet-cetinkaya** [comment]
I used this way in my own project. (TranslateYamlHttpLoader and yaml are optional, of course.)

src\app\providers\translation.ts
```ts
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { importProvidersFrom } from '@angular/core';
import { TranslateLoader, TranslateModule, TranslateModuleConfig } from '@ngx-translate/core';
import { Observable, map } from 'rxjs';
import { parse } from 'yaml';

class TranslateYamlHttpLoader implements TranslateLoader {
  constructor(
    private httpClient: HttpClient,
    public path: string = '/assets/i18n/',
  ) {}

  public getTranslation(lang: string): Observable<unknown> {
    return this.httpClient.get(`${this.path}${lang}.yaml`, { responseType: 'text' }).pipe(map((data) => parse(data)));
  }
}

const config: TranslateModuleConfig = {
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: (httpClient: HttpClient) => new TranslateYamlHttpLoader(httpClient),
    deps: [HttpClient],
  },
};

export function provideTranslation() {
  return importProvidersFrom([HttpClientModule, TranslateModule.forRoot(config)]);
}
```

src\app\app.config.ts
```ts
import { provideTranslation } from './providers/translation';

export const appConfig: ApplicationConfig = {
  providers: [provideTranslation()],
};
```

**Comment by shahmaulik1991** [comment]
//app.config.ts
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideAnimations } from '@angular/platform-browser/animations';
import { HttpBackend, HttpClient, HttpClientModule, provideHttpClient } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export const provideTranslation = () => ({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient],
  },
});

export function HttpLoaderFactory(http: HttpClient) {
  return  new  TranslateHttpLoader(http, './assets/i18n/', '.json');
}
export const appConfig: ApplicationConfig = {
  providers: [provideRouter(routes),provideAnimations(),provideHttpClient(),importProvidersFrom(HttpClientModule), importProvidersFrom([TranslateModule.forRoot(provideTranslation())
  ]),],
};
//particular components
import { TranslateModule, TranslateService } from '@ngx-translate/core';
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [TranslateModule]
})
export class HomeComponent {
constructor(
   public translate: TranslateService
  ) {}

this.translate.setDefaultLang('en'); //ngonint

}

**Comment by shahmaulik1991** [comment]
app.config.ts
import { ApplicationConfig, importProvidersFrom } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideAnimations } from '@angular/platform-browser/animations';
import { HttpBackend, HttpClient, HttpClientModule, provideHttpClient } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

export const provideTranslation = () => ({
defaultLanguage: 'en',
loader: {
provide: TranslateLoader,
useFactory: HttpLoaderFactory,
deps: [HttpClient],
},
});

export function HttpLoaderFactory(http: HttpClient) {
return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}
export const appConfig: ApplicationConfig = {
providers: [provideRouter(routes),provideAnimations(),provideHttpClient(),importProvidersFrom(HttpClientModule), importProvidersFrom([TranslateModule.forRoot(provideTranslation())
]),],
};
//particular components
import { TranslateModule, TranslateService } from '@ngx-translate/core';
https://github.com/component({
selector: 'app-home',
standalone: true,
imports: [TranslateModule]
})
export class HomeComponent {
constructor(
public translate: TranslateService
) {}

this.translate.setDefaultLang('en'); //ngonint
}

<div class="w-100 title-name">{{'login.title' | translate }}</div>

**Comment by ArmandoxxXD** [comment]
I create a module with the command 'ng g module tranlate', there I put this code: 

tranlate.module.ts:
 ```
import { NgModule } from '@angular/core';
    import { CommonModule } from '@angular/common';
    import { HttpClient,HttpClientModule } from '@angular/common/http';
    import { TranslateModule, TranslateLoader } from '@ngx-translate/core';
    import { TranslateHttpLoader } from '@ngx-translate/http-loader';
    
    export function HttpLoaderFactory(http: HttpClient) {
      return new TranslateHttpLoader(http,'./assets/languages/','.json');
    }
    
    @NgModule({
      declarations: [],
      imports: [
        CommonModule,
        HttpClientModule,
        TranslateModule.forRoot({
          loader: {
            provide:TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
          }
        })
      ],
      exports: [
        CommonModule,
        HttpClientModule,
        TranslateModule
      ]
    })
    export class TranlateModule { }
```

with that done I can now import the module into more different components that I use for processing and it works , for example this is one of my components where I use the translation 

information.component.ts: 

```
import { Component } from '@angular/core';
import { TranlateModule } from '../../module/tranlate/tranlate.module';

@Component({
  selector: 'app-information',
  standalone: true,
  imports: [
    TranlateModule
  ],
  templateUrl: './information.component.html',
  styleUrl: './information.component.css'
})
export class InformationComponent {

}
```

And if it is useful to you, this is my component where I have the logic to change languages

main.component.ts:
 
```
import { Component, Inject} from '@angular/core';
import { MenuComponent } from '../menu/menu.component';
import { InformationComponent } from '../information/information.component';
import { RouterOutlet } from '@angular/router';
import { CommonModule, DOCUMENT } from '@angular/common';
import { TranslateService } from '@ngx-translate/core';

@Component({
  selector: 'app-main',
  standalone: true,
  imports: [
    MenuComponent,
    InformationComponent,
    RouterOutlet,
    CommonModule,
  ],
  templateUrl: './main.component.html',
  styleUrl: './main.component.css'
})
export class MainComponent{
englishLanguageEnabled:Boolean = false;

    
constructor(@Inject(DOCUMENT) private document: Document, private translate: TranslateService){
 this.translate.addLangs(['en','es']);
 const localStorage = document.defaultView?.localStorage;
 
    if(localStorage) {
        const lang = localStorage.getItem('lang');
        if (lang) {
          this.englishLanguageEnabled = lang === 'en';
          this.translate.use(lang);
        } else {
          const browserLang = this.translate.getBrowserLang();
          const langToUse = /(en|es)/.test(browserLang!) ? browserLang : 'en';
          this.translate.use(langToUse!);
        }
      }
}

toggleLanguages(): void {
  this.englishLanguageEnabled = !this.englishLanguageEnabled;
  if (this.englishLanguageEnabled) {
    this.loadLanguageEn();
  } else {
    this.loadLanguageEs();
  }
}

loadLanguageEn() {
  const lang = 'en';
  localStorage.setItem("lang",lang);
  this.translate.use(lang);
}
 
loadLanguageEs() {
  const lang = 'es';
  localStorage.setItem("lang",lang);
  this.translate.use(lang);
}

}
```

**Comment by haykeminyan** [comment]
@siloimwald thank you very much! Your approach saves me a lot of time! It's working in 17 version!

**Comment by AlineCross** [comment]
> Here is how it worked for me... app.config.ts
> 
> ```
> // AoT requires an exported function for factories
> export function HttpLoaderFactory(httpClient: HttpClient) {
>   return  new  TranslateHttpLoader(httpClient, './assets/i18n/', '.json');
> }
> 
> export const provideTranslation = () => ({
>   defaultLanguage: 'en',
>   loader: {
>     provide: TranslateLoader,
>     useFactory: HttpLoaderFactory,
>     deps: [HttpClient],
>   },
> });
> 
> export const appConfig: ApplicationConfig = {
>   providers: [
>     provideAnimations(), // required animations providers
>     provideHttpClient(),
>     importProvidersFrom([
>       HttpClientModule, 
>       TranslateModule.forRoot(provideTranslation())
>     ]),
>     provideRouter(routes),
>     
>   ]
> };
> ```

You deserve all the praise in the world - that worked perfectly for me!

**Comment by maozhenhua2** [comment]
`
// app.config
import {ApplicationConfig, importProvidersFrom, provideZoneChangeDetection} from '@angular/core';
import {provideRouter} from '@angular/router';

import {routes} from './app.routes';
import {HttpClient, HttpClientModule, provideHttpClient} from "@angular/common/http";
import {TranslateHttpLoader} from '@ngx-translate/http-loader';
import {TranslateLoader, TranslateModule} from "@ngx-translate/core";


export const provideTranslation = () => ({
  defaultLanguage: 'en',
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient],
  },
});

export function HttpLoaderFactory(httpClient: HttpClient) {
  return new TranslateHttpLoader(httpClient, './assets/i18n/', '.json?' + new Date().getTime());
}

export const appConfig: ApplicationConfig = {
  providers: [
    provideHttpClient(),
    provideZoneChangeDetection({eventCoalescing: true}),
    importProvidersFrom([
      HttpClientModule,
      TranslateModule.forRoot(provideTranslation())
    ]),
    provideRouter(routes),
  ]
};
`

`
// login.component
import {Component} from '@angular/core';
import {TranslateModule, TranslateService} from "@ngx-translate/core";

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [
    TranslateModule
  ],
  templateUrl: './login.component.html',
  styleUrl: './login.component.scss'
})
export class LoginComponent {
  // constructor(private translate: TranslateService) {
  // }

  ngOnInit(): void {
    // this.translate.use('cn');
  }
}

`

brower info
`
Error: NG0203: inject() must be called from an injection context such as a constructor, a factory function, a field initializer, or a function used with `runInInjectionContext`. Find more at https://angular.dev/errors/NG0203
`

package.json
`
"dependencies": {
    "@angular/animations": "^18.0.0",
    "@angular/common": "^18.0.0",
    "@angular/compiler": "^18.0.0",
    "@angular/core": "^18.0.0",
    "@angular/forms": "^18.0.0",
    "@angular/platform-browser": "^18.0.0",
    "@angular/platform-browser-dynamic": "^18.0.0",
    "@angular/router": "^18.0.0",
    "@ngx-translate/core": "^15.0.0",
    "@ngx-translate/http-loader": "^8.0.0",
    "rxjs": "~7.8.0",
    "tslib": "^2.3.0",
    "zone.js": "~0.14.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^18.0.3",
    "@angular/cli": "^18.0.3",
    "@angular/compiler-cli": "^18.0.0",
    "@types/jasmine": "~5.1.0",
    "jasmine-core": "~5.1.0",
    "karma": "~6.4.0",
    "karma-chrome-launcher": "~3.2.0",
    "karma-coverage": "~2.2.0",
    "karma-jasmine": "~5.1.0",
    "karma-jasmine-html-reporter": "~2.1.0",
    "typescript": "~5.4.2"
  }
`

**Comment by MarikaKonturova** [comment]
worked for angular 18 (^18.0.4)

app.config.ts
---
```
import {
  ApplicationConfig,
  importProvidersFrom,
  provideZoneChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';

import { HttpClient, HttpClientModule } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { routes } from './app.routes';

function HttpLoaderFactory(http: HttpClient) {
  return new TranslateHttpLoader(http, '../assets/i18n/', '.json');
}
export const provideTranslation = () => ({
  loader: {
    provide: TranslateLoader,
    useFactory: HttpLoaderFactory,
    deps: [HttpClient],
  },
});
export const appConfig: ApplicationConfig = {
  providers: [
    provideZoneChangeDetection({ eventCoalescing: true }),
    importProvidersFrom([
      HttpClientModule,
      TranslateModule.forRoot(provideTranslation()),
    ]),
    provideRouter(routes),
  ],
};
```
app.component.ts
---
```
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { TranslateModule, TranslateService } from '@ngx-translate/core';
import { MainComponent } from 'components/main/main.component';
import { SpacebgComponent } from 'components/spacebg/spacebg.component';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet, MainComponent, SpacebgComponent, **_TranslateModule_**],
  templateUrl: './app.component.html',
  styleUrl: './app.component.scss',
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AppComponent {
  constructor(public translate: TranslateService) {
    translate.addLangs(['en', 'ru']);
    translate.setDefaultLang('ru');

    const browserLang = translate.getBrowserLang();
    translate.use(browserLang?.match(/en|ru/) ? browserLang : 'ru');
  }
}
```
app.component.html
---
`{{ "helloworld or any other word from your json" | translate }}`

**Comment by yl-endress** [comment]
+1
