### ISSUE TITLE
Update Ionic 2 example to RC.0

### ISSUE THREAD

**Issue by NoNameProvided** [ocombe/ng2-translate#248]
**Current behavior**

Readme explains bootstrapping for Ionic Beta

**Expected/desired behavior**

Readme explains bootstrapping for Ionic RC

Edit: Trying to put `TranslateModule.forRoot()` into `imports` in _app.module.ts_ will kill the _ngc_.

**Comment by ocombe** [comment]
Yes, it's definitely on my todo list :)

**Comment by DreamitMauri** [comment]
Any quick tips on how to get it to work with Ionic RC.0?

**Comment by ocombe** [comment]
I suppose it should work just like the regular documentation for non ionic apps, just import the module and call `forRoot()` (with or without parameters, depending on what you need, check for the readme for that)

**Comment by DreamitMauri** [comment]
Unfortunately it doesn't work. I get 
`ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol AppModule in xxx/.tmp/app/app.module.ts, resolving symbol AppModule in xxx/.tmp/app/app.module.ts`

Using 
`imports: [
        IonicModule.forRoot(MyApp),
        HttpModule,
        TranslateModule.forRoot()
],`

**Comment by chiccorusso** [comment]
Hi! That's #218 .

**Comment by DreamitMauri** [comment]
Ah, so it is. Thank you.

**Comment by danielgolub** [comment]
On my side it writes:
[16:58:58]  Error: Module /node_modules/ng2-translate/ng2-translate.js does not export TranslateLoader (imported by /.tmp/app/app.module.js)

**Comment by membersheep** [comment]
TranslateLoader and TranslateStaticLoader can be imported from 'ng2-translate/src/translate.service', but calling TranslateModule.forRoot() will cause the build process to fail.

**Comment by derksacklowski** [comment]
dev mode works fine if we include {TranslateLoader , TranslateStaticLoader, TranslateService } from 'ng2-translate/src/translate.service',

"ionic build" fails

ngc error: Error: Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 30:23 in the original .ts file), resolving symbol AppModule in C:/Users/dsc/dev/23_angular__rhenus__information/.tmp/app/app.module.ts
    at simplifyInContext (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\static_reflector.js:469:23)
    at StaticReflector.simplify (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\static_reflector.js:472:22)
    at StaticReflector.annotations (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\static_reflector.js:61:36)
    at _loop_1 (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\codegen.js:53:54)
    at CodeGenerator.readFileMetadata (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\codegen.js:66:13)
    at C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\codegen.js:100:74
    at Array.map (native)
    at CodeGenerator.codegen (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\codegen.js:100:35)
    at codegen (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\compiler-cli\src\main.js:7:81)
    at Object.main (C:\Users\dsc\dev\23_angular__rhenus__information\node_modules\@angular\tsc-wrapped\src\main.js:30:16)

**Comment by jafaripur** [comment]
Same for me.
```
Error: Module node_modules/ng2-translate/ng2-translate.js does not export TranslateLoader (imported by /home/SideMenu/.tmp/app/app.module.js)
```

**Comment by derksacklowski** [comment]
https://github.com/ocombe/ng2-translate/issues/218 has some sort of solution

**Comment by NoNameProvided** [comment]
Thanks for the quick fix!

**Comment by Eagleseb** [comment]
Be careful, for ionic the configuration should be : 
`useFactory: (http: Http) => new TranslateStaticLoader(http, 'assets/i18n', '.json'),`
instead of
`useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),`

(mind the slash before assets)
