### ISSUE TITLE
Uncaught TypeError: ctorParameters.map is not a function

### ISSUE THREAD

**Issue by mmathys** [ocombe/ng2-translate#386]
**I'm submitting a...** 

* [x] support request

**Current behavior**
When importing `TranslateModule.forRoot()` in the imports, it throws this error:

```
Uncaught TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (http://localhost:3000/vendor.bundle.js:34588:45)
    at Reflector.parameters (http://localhost:3000/vendor.bundle.js:34723:44)
    at CompileMetadataResolver.getDependenciesMetadata (http://localhost:3000/vendor.bundle.js:11423:54)
    at CompileMetadataResolver.getTypeMetadata (http://localhost:3000/vendor.bundle.js:11388:26)
    at http://localhost:3000/vendor.bundle.js:11531:41
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (http://localhost:3000/vendor.bundle.js:11511:19)
    at http://localhost:3000/vendor.bundle.js:11209:71
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://localhost:3000/vendor.bundle.js:11200:44)
    at RuntimeCompiler._compileComponents (http://localhost:3000/vendor.bundle.js:17531:47)
    at RuntimeCompiler._compileModuleAndComponents (http://localhost:3000/vendor.bundle.js:17469:37)
    at RuntimeCompiler.compileModuleAsync (http://localhost:3000/vendor.bundle.js:17460:21)
    at PlatformRef_._bootstrapModuleWithZone (http://localhost:3000/vendor.bundle.js:26088:25)
    at PlatformRef_.bootstrapModule (http://localhost:3000/vendor.bundle.js:26070:21)
    at HTMLDocument.main (http://localhost:3000/main.bundle.js:8610:10)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:15381:35)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:15270:47)
    at HTMLDocument.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:15451:33)
```

I am ONLY importing the module first and then adding to the import array with the `forRoot()` function.

**Expected/desired behavior**

It shouldn't throw this error.

**What is the expected behavior?**

It should just compile, do nothing. I am using webpack btw.

**Please tell us about your environment:**

* **Webpack version:** 2.1.0-beta.25

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.1.1
 
* **Browser:** Chrome 55
 
* **Language:** TypeScript 2.1.4

**Comment by ocombe** [comment]
This error seems to be a problem with angular < 2.2.3.
Can you upgrade to 2.2.3 +?

**Comment by mmathys** [comment]
Wow, that was fast! Yes, it worked! Thanks so much!!

**Comment by ocombe** [comment]
Awesome :)
