### ISSUE TITLE
Getting error while incorporating ng2-translate.

### ISSUE THREAD

**Issue by amoldorkar-ezest** [ocombe/ng2-translate#63]
```
    System.config({
        packages: {
            assets: {
                format: 'register',
                defaultExtension: 'js'
            }
        },
        map: {
            moment: 'node_modules/moment/moment.js',
            'ng2-translate': 'node_modules/ng2-translate'
        }

    });
    System.import('assets/main')
            .then(null, console.error.bind(console));
```

This is my system.config script, and I got error on browser's console is 
1. Uncaught (in promise) TypeError: object is not a constructor
   at then (native)
2. angular2-polyfills.js:1243 SyntaxError: Unexpected token <
   Evaluating http://localhost:3000/node_modules/ng2-translate/ng2-translate
   Error loading http://localhost:3000/assets/main.js
   at SystemJSLoader.__exec (http://localhost:3000/node_modules/systemjs/dist/system.src.js:1395:16)
   at entry.execute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3521:16)
   at linkDynamicModule (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3126:32)
   at link (http://localhost:3000/node_modules/systemjs/dist/system.src.js:2969:11)
   at Object.execute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:3301:13)
   at doDynamicExecute (http://localhost:3000/node_modules/systemjs/dist/system.src.js:703:25)
   at link (http://localhost:3000/node_modules/systemjs/dist/system.src.js:905:20)
   at doLink (http://localhost:3000/node_modules/systemjs/dist/system.src.js:557:7)
   at updateLinkSetOnLoad (http://localhost:3000/node_modules/systemjs/dist/system.src.js:605:18)
   at http://localhost:3000/node_modules/systemjs/dist/system.src.js:417:11

Zone.run    @   angular2-polyfills.js:1243
zoneBoundFn @   angular2-polyfills.js:1220
lib$es6$promise$$internal$$tryCatch @   angular2-polyfills.js:468
lib$es6$promise$$internal$$invokeCallback   @   angular2-polyfills.js:480
lib$es6$promise$$internal$$publish  @   angular2-polyfills.js:451
lib$es6$promise$$internal$$publishRejection @   angular2-polyfills.js:401
(anonymous function)    @   angular2-polyfills.js:123
Zone.run    @   angular2-polyfills.js:1243
zoneBoundFn @   angular2-polyfills.js:1220
lib$es6$promise$asap$$flush @   angular2-polyfills.js:262

**Comment by ocombe** [comment]
Hello, it looks like an error with the order of your scripts and the version of es6-shim: https://github.com/blacksonic/angular2-es6-starter/issues/1
You should update to beta 11 and update the es6-shim as well, and let me know if it works.

**Comment by guillaumeleone** [comment]
Hi, I use angular-cli, and I'm trying to use ng2-translate module, but I've got this same error when I ran my project.

**Comment by ocombe** [comment]
@guillaumeleone Yes the angular-cli doesn't work with libraries published with typescript definitions (but without typescript sources), @jkuri was supposed to work on that but I have no idea where it stands right now...

**Comment by ocombe** [comment]
Closing this old issue, let me know if I should reopen it.
